### ISSUE TITLE
Improve error message for failed tredlyfile validation

### ISSUE THREAD

**Issue by laurieodgers** [tredly/tredly#93]
The following is output when the user uses GB instead of G for maxRam or maxHdd. This should be improved into a nicer error message for the user.

--------------------
Traceback (most recent call last):
 File "/usr/local/sbin/tredly-build", line 213, in <module>
   actionObj = actionMod(args.subject, args.target, args.identifier, actionArgs)
 File "/usr/local/lib/tredly-build/actions/create.py", line 37, in __init__
   self.createContainer(actionArgs['containerName'], actionArgs['partitionName'], actionArgs['path'], actionArgs['ip4Addr'])
 File "/usr/local/lib/tredly-build/actions/create.py", line 57, in createContainer
   builtins.tredlyFile = TredlyFile(tredlyFilePath)
 File "/usr/local/lib/tredly/python-common/objects/tredly/tredlyfile.py", line 19, in __init__
   self.json = self.parser.read()
 File "/usr/local/lib/tredly/python-common/objects/tredly/parser/tredlyfilefile/__init__.py", line 228, in read
   funcs[key](val)
 File "/usr/local/lib/tredly/python-common/objects/tredly/parser/tredlyfilefile/__init__.py", line 176, in add
   val = str(int(value) * 1024) + 'M'
ValueError: invalid literal for int() with base 10: '30GB'

**Comment by laurieodgers** [comment]
This came to me 2nd hand and I cannot reproduce this issue. If anyone comes across this bug please open another ticket.
